id: AF76AE97A
title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful Sādhana
  of Mañjuśrī'
type: translation
pechas:
- I9D83CDF0
- IE5E1D46B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:37.513341
  last_modified_at: 2023-01-04 12:49:37.513350
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I9D83CDF0/2E18: '4884'
  IE5E1D46B/A42E: '4884'
